version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      # Prefix all commit messages with "ci(dep-bot): for tooling"
      prefix: 'ci(dep-bot): '
  - package-ecosystem: 'npm'
    directory: '/infra'
    schedule:
      interval: 'daily'
    commit-message:
      # Prefix all commit messages with "ci(dep-bot): for tooling"
      prefix: 'ci(dep-bot): '